categories_map = {
    "JavaScript": "Languages",
    "React.js": "Frameworks",
    "CSS": "Languages",
    "HTML": "Languages",
    "design": "Soft Skills",
    "Python": "Languages",
    "troubleshooting": "Soft Skills",
    "TypeScript": "Languages",
    "Java": "Languages",
    "Node.js": "Runtimes",
    "Deno": "Runtimes",
    "Bun": "Runtimes",
    "design": "Soft Skills",
    "testing": "Processes",
    "frontend": "Specializations",
    "fullstack": "Specializations",
    "UI/UX": "Processes",
    "AWS": "Cloud Service Providers",
    "Angular": "Frameworks",
    "Ajax": "Techniques",
    "SQL": "Languages",
    "CI/CD": "Practices",
    "MySQL": "Databases",
    "agile": "Methodologies",
    "backend": "Specializations",
    "machine learning": "Knowledge Domains",
    "scalability": "Principles",
    "DevOps": "Specializations",
    "Bootstrap": "Frameworks",
    "clean code": "Principles",
    "innovation": "Personality Traits",
    "relational databases": "Databases",
    "PHP": "Languages",
    "interpersonal skills": "Soft Skills",
    "mobile": "Platforms",
    "Android": "Operating Systems",
    "iOS": "Operating Systems",
    "Ruby": "Languages",
    "mentoring": "Soft Skills",
    "collaboration skills": "Soft Skills",
    "time management": "Soft Skills",
    "Swift": "Languages",
    "Windows": "Operating Systems",
    "EC2": "AWS Services",
    "flexibility": "Personality Traits",
    "Postman": "Tool",
    "Salesforce": "Customer Relationship Management",
    "Kotlin": "Languages",
    "SVN": "Version Control Systems",
    "Ansible": "Configuration Management",
    "J2EE": "Specifications",
    "Visual Studio": "Integrated Development Environments",
    "Spring": "Frameworks",
    "BitBucket": "Version Control Systems",
    "Spring Boot": "Frameworks",
    "ECS": "AWS Services",
    "planning": "Soft Skills",
    "performance": "Principles",
    "gRPC": "Frameworks",
    "Photoshop": "Design Tool",
    "system design": "Knowledge Domains",
    "visualization": "Processes",
    "Perl": "Languages",
    "reusability": "Principles",
    "positive attitude": "Personality Traits",
    "detail-oriented": "Personality Traits",
    "maintainability": "Principles",
    "network security": "Knowledge Domains",
    "Selenium": "Automation",
    "C": "Languages",
    "C++": "Languages",
    "self-starter": "Personality Traits",
    "SASS": "CSS Preprocessors",
    "SQL Server": "Databases",
    "usability": "Principles",
    "prototyping": "Processes",
    "Scrum": "Methodologies",
    "Django": "Frameworks",
    "Unix": "Operating Systems",
    "jQuery": "Libraries",
    "NoSQL": "Databases",
    "React Native": "Frameworks",
    "PostgreSQL": "Databases",
    "REST": "Architecture",
    "microservices": "Architecture",
    "mangement": "Soft Skills",
    "Docker": "Containerization",
    "Kubernetes": "Containerization",
    "Vue.js": "Frameworks",
    "MongoDB": "Databases",
    "Terraform": "Build Tools",
    "Oracle": "Cloud Service Providers",
    "Redis": "Databases",
    "accessibility": "Principles",
    ".NET": "Frameworks",
    "distributed systems": "Knowledge Domains",
    "data structures": "Knowledge Domains",
    "design patterns": "Knowledge Domains",
    "documentation": "Processes",
    "code review": "Processes",
    "Jira": "Project Management",
    "Azure": "Cloud Service Providers",
    "problem-solving": "Soft Skills",
    "Go": "Languages",
    "Splunk": "Log Management",
    "XML": "Languages",
    "GraphQL": "Query Languages",
    "LINQ": "Query Languages",
    "Linux": "Operating Systems",
    "reliability": "Personality Traits",
    "attention to detail": "Personality Traits",
    "monitoring": "Processes",
    "project management": "Processes",
    "mentorship": "Soft Skills",
    "Webpack": "Build Tools",
    "Maven": "Build Tools",
    "entity framework": "Object Relational Mapper",
    "organizational skills": "Soft Skills",
    "Git": "Version Control Systems",
    "GCP": "Cloud Service Providers",
    "C#": "Languages",
    "AI": "Knowledge Domains",
    "ASP.NET": "Frameworks",
    "Hadoop": "Distributed Computing",
    "Figma": "Design Tools",
    "SOA": "Architecture",
    "Grafana": "Visualization Tools",
    "Cassandra": "Databases",
    "Saml": "Languages",
    "Flask": "Frameworks",
    "MVC": "Design Pattern",
    "functionality": "Principles",
    "PL/SQL": "Query Languages",
    "integration testing": "Processes",
    "HTTP": "Protocols",
    "HTTPS": "Protocols",
    "Ruby on Rails": "Frameworks",
    "SOAP": "Protocols",
    "documentation": "Processes",
    "analytical skills": "Soft Skills",
    "time-management": "Soft Skills",
    "management": "Soft Skills",
    "QA": "Specializations",
    "Kafka": "Messaging Systems",
    "VB.NET": "Languages",
    "RabbitMQ": "Messaging Systems",
    "Next.js": "Frameworks",
    "communication": "Soft Skills",
    "collaboration": "Soft Skills",
    "maintenance": "Processes",
    "unit testing": "Processes",
    "algorithms": "Knowledge Domains",
    "test-driven development": "Methodologies",
    "GitHub": "Version Control Systems",
    "fast-paced": "Personality Traits",
    "self-motivated": "Personality Traits",
    "data analysis": "Processes",
    "JUnit": "Testing Frameworks",
    "Selenium": "Testing Frameworks",
    "Jest": "Testing Frameworks",
    "Elasticsearch": "Search Engines",
    "automated testing": "Processes",
    "Drupal": "Content Management Systems",
    "networking": "Specializations",
    "computer vision": "Knowledge Domains",
    "creativity": "Personality Traits",
    "GitLab": "Version Control Systems",
    "S3": "AWS Services",
    "passionate": "Personality Traits",
    "empathy": "Personality Traits",
    "responsive web design": "Practices",
    "XML": "Data Formats",
    "JSON": "Data Formats",
    "automation": "Processes",
    "deployment": "Processes",
    "Jenkins": "Automation",
    "security": "Knowledge Domains",
    "cybersecurity": "Knowledge Domains",
    "teamwork": "Personality Traits",
    "training": "Soft Skills",
    "Redux": "Global State Management",
    "Wordpress": "Content Management Systems",
    "networking": "Knowledge Domains",
    "optimization": "Processes",
    "Hibernate": "Object Relational Mapper",
    "SEO": "Processes",
    "IIS": "Servers",
    "leadership": "Soft Skills",
    "database design": "Processes",
    "configuration": "Processes",
    "performance tuning": "Processes",
    "availability": "Principles",
    "product management": "Processes",
    "compliance": "Principles",
    "npm": "Package Managers",
    "leadership": "Soft Skills",
    "efficiency": "Personality Traits",
    "requirements gathering": "Processes",
    "requirements analysis": "Processes",
    "PowerShell": "Scripting Languages",
    "TFS": "Version Control Systems",
    "WCF": "Frameworks",
    "data modeling": "Processes",
    "SSRS": "Reporting Tool",
    "Sharepoint": "Content Management Systems",
    "Lambda": "AWS Services",
    "cross-browser compatibility": "Principles",
    "scripting": "Processes",
    "Confluence": "Project Management",
    "innovative": "Personality Traits",
    "ASP.NET MVC": "Frameworks",
    "DynamoDB": "AWS Services",
    "RDS": "AWS Services",
    "graphic design": "Specializations",
    "Apache": "Servers",
    "Google Analytics": "Analysis Tools",
    "root cause analysis": "Processes",
    "configuration management": "Processes",
    "change management": "Processes",
    "JSP": "Template Engines",
    "T-SQL": "Query Languages",
    "bash": "Scripting Languages",
    "mathematics": "Knowledge Domains",
    "Kanban": "Project Management",
    "Cypress": "Testing Frameworks",
    "analytical": "Personality Traits",
    "adaptibility": "Personality Traits",
    "Eclipse": "Integrated Development Environments",
    "penetration testing": "Processes",
    "motivated": "Personality Traits",
    "LESS": "CSS Preprocessors",
    "WPF": "Frameworks",
    "regression testing": "Processes",
    "information security": "Knowledge Domains",
    "performance testing": "Processes",
    "Spark": "Distributed Computing",
    "XSLT": "Languages",
    "Express.js": "Frameworks",
    "Illustrator": "Design Tools",
    "Cucumber": "Testing Frameworks",
}
