categories_map = {
    "JavaScript": "Language",
    "React.js": "Framework",
    "CSS": "Language",
    "HTML": "Language",
    "design": "Soft Skill",
    "Python": "Language",
    "troubleshooting": "Soft Skill",
    "TypeScript": "Language",
    "Java": "Language",
    "Node.js": "Runtime",
    "Deno": "Runtime",
    "Bun": "Runtime",
    "design": "Soft Skill",
    "testing": "Soft Skill",
    "frontend": "Specialization",
    "fullstack": "Specialization",
    "UI/UX": "Specialization",
    "AWS": "Cloud Service Provider",
    "Angular": "Framework",
    "Ajax": "Technique",
    "SQL": "Language",
    "CI/CD": "Practice",
    "MySQL": "Database",
    "agile": "Methodology",
    "backend": "Specialization",
    "machine learning": "Knowledge Domain",
    "scalability": "Principle",
    "DevOps": "Specialization",
    "Bootstrap": "Framework",
    "clean code": "Principle",
    "innovation": "Personality Trait",
    "relational databases": "Database",
    "PHP": "Language",
    "interpersonal skills": "Soft Skill",
    "mobile": "Platform",
    "Android": "Operating System",
    "iOS": "Operating System",
    "Ruby": "Language",
    "mentoring": "Soft Skill",
    "collaboration skills": "Soft Skill",
    "time management": "Soft Skill",
    "Swift": "Language",
    "Windows": "Operating System",
    "EC2": "AWS Service",
    "flexibility": "Personality Trait",
    "Postman": "Tool",
    "Salesforce": "Customer Relationship Management",
    "Kotlin": "Language",
    "SVN": "Version Control System",
    "Ansible": "Configuration Management",
    "J2EE": "Specification",
    "Visual Studio": "Integrated Development Environment",
    "Spring": "Framework",
    "BitBucket": "Version Control System",
    "Spring Boot": "Framework",
    "ECS": "AWS Service",
    "planning": "Soft Skill",
    "performance": "Principle",
    "gRPC": "Framework",
    "Photoshop": "Design Tool",
    "system design": "Specialization",
    "infrastructure": "Specialization",
    "visualization": "Process",
    "Perl": "Language",
    "reusability": "Principle",
    "positive attitude": "Personality Trait",
    "detail-oriented": "Personality Trait",
    "maintainability": "Principle",
    "network security": "Knowledge Domain",
    "Selenium": "Automation",
    "C": "Language",
    "C++": "Language",
    "self-starter": "Personality Trait",
    "SASS": "CSS Preprocessor",
    "SQL Server": "Database",
    "usability": "Principle",
    "prototyping": "Process",
    "Scrum": "Methodology",
    "Django": "Framework",
    "Unix": "Operating System",
    "jQuery": "Library",
    "NoSQL": "Database",
    "React Native": "Framework",
    "PostgreSQL": "Database",
    "REST": "Architecture",
    "microservices": "Architecture",
    "mangement": "Soft Skill",
    "Docker": "Containerization",
    "Kubernetes": "Containerization",
    "Vue.js": "Framework",
    "MongoDB": "Database",
    "Terraform": "Build Tool",
    "Oracle": "Cloud Service Provider",
    "Redis": "Database",
    "accessibility": "Principle",
    ".NET": "Framework",
    "distributed systems": "Knowledge Domain",
    "data structures": "Knowledge Domain",
    "design patterns": "Knowledge Domain",
    "documentation": "Process",
    "code review": "Process",
    "Jira": "Project Management",
    "Azure": "Cloud Service Provider",
    "problem-solving": "Soft Skill",
    "Go": "Language",
    "Splunk": "Log Management",
    "XML": "Language",
    "GraphQL": "Query Language",
    "LINQ": "Query Language",
    "Linux": "Operating System",
    "reliability": "Personality Trait",
    "attention to detail": "Personality Trait",
    "monitoring": "Process",
    "project management": "Process",
    "mentorship": "Soft Skill",
    "Webpack": "Build Tool",
    "Maven": "Build Tool",
    "Entity Framework": "Framework",
    "organizational skills": "Soft Skill",
    "Git": "Version Control System",
    "GCP": "Cloud Service Provider",
    "C#": "Language",
    "AI": "Knowledge Domain",
    "ASP.NET": "Framework",
    "Hadoop": "Tool",
    "Figma": "Design Tool",
    "SOA": "Architecture",
    "Grafana": "Tool",
    "Cassandra": "Database",
    "Saml": "Language",
    "Flask": "Framework",
    "MVC": "Design Pattern",
    "functionality": "Principle",
    "PL/SQL": "Query Language",
    "integration testing": "Process",
    "HTTP": "Protocol",
    "HTTPS": "Protocol",
    "Ruby on Rails": "Framework",
    "SOAP": "Protocol",
    "documentation": "Process",
    "analytical skills": "Soft Skill",
    "time-management": "Soft Skill",
    "management": "Soft Skill",
    "QA": "Specialization",
    "Kafka": "Messaging System",
    "VB.NET": "Language",
    "RabbitMQ": "Messaging System",
    "Next.js": "Framework",
    "communication": "Soft Skill",
    "collaboration": "Soft Skill",
    "maintenance": "Process",
    "unit testing": "Process",
    "algorithms": "Knowledge Domain",
    "test-driven development": "Methodology",
    "GitHub": "Version Control System",
    "fast-paced": "Personality Trait",
    "self-motivated": "Personality Trait",
    "data analysis": "Process",
    "JUnit": "Testing Framework",
    "Selenium": "Testing Framework",
    "Jest": "Testing Framework",
    "Elasticsearch": "Search Engine",
    "automated testing": "Process",
    "Drupal": "Content Management System",
    "networking": "Specialization",
    "computer vision": "Computer Science Topic",
    "creativity": "Personality Trait",
    "GitLab": "Version Control System",
    "S3": "AWS Service",
    "passionate": "Personality Trait",
    "empathy": "Personality Trait",
    "responsive web design": "Practice",
    "XML": "Data Format",
    "JSON": "Data Format",
    "automation": "Process",
    "deployment": "Process",
    "Jenkins": "Automation",
    "security": "Knowledge Domain",
    "cybersecurity": "Knowledge Domain",
    "teamwork": "Personality Trait",
    "training": "Soft Skill",
    "Redux": "Global State Management",
    "Wordpress": "Content Management System",
    "networking": "Knowledge Domain",
    "optimization": "Process",
    "Hibernate": "Object Relational Mapping",
    "SEO": "Process",
    "IIS": "Server",
    "leadership": "Soft Skill",
    "database design": "Process",
    "configuration": "Process",
    "performance tuning": "Process",
    "availability": "Principle",
    "product managmeent": "Specialization",
    "compliance": "Principle",
    "npm": "Package Manager",
    "leadership": "Soft Skill",
    "efficiency": "Personality Trait",
    "requirements gathering": "Process",
    "requirements analysis": "Process",
    "PowerShell": "Scripting Language",
    "TFS": "Version Control System",
    "WCF": "Framework",
    "data modeling": "Process",
    "SSRS": "Reporting Tool",
    "Sharepoint": "Content Management System",
    "Lambda": "AWS Service",
}
