import json
from fuzzywuzzy import fuzz

filename = "dataset_indeed-scraper_2023-09-16_01-10-37-409"

with open(
    f"keywords_extracted/{filename}.json",
    "r",
    encoding="utf-8",
) as json_file:
    data = json.load(json_file)

keyword_map = {}

for keyword_list in data:
    for keyword in keyword_list:
        keyword = keyword.lower()
        if keyword in keyword_map:
            keyword_map[keyword] += 1
        else:
            keyword_map[keyword] = 1


one_to_many_map = {
    "html/css": ["html", "css"],
    "spring boot": ["spring", "spring boot"],
    "c/c++": ["c", "c++"],
}

similarity_map = {
    "front-end": "frontend",
    "reactjs": "react",
    "css3": "css",
    "html5": "html",
    "angularjs": "angular",
    "angular.js": "angular",
    "react.js": "react",
    "node": "node.js",
    "nodejs": "node.js",
    "node js": "node.js",
    "continuous integration": "ci/cd",
    "continuous deployment": "ci/cd",
    "user experience": "ui/ux",
    "ux": "ui/ux",
    "user experiences": "ui/ux",
    "ui design": "ui/ux",
    "ux design": "ui/ux",
    "golang": "go",
    "oop": "object-oriented programming",
    "object oriented programming": "object-oriented programming",
    "object-oriented design": "object-oriented programming",
    "amazon web services": "aws",
    "google cloud": "gcp",
    "google cloud platform": "gcp",
    "front-end technologies": "frontend",
    "front-end development": "frontend",
    "frontend development": "frontend",
    "back-end": "backend",
    "back-end development": "backend",
    "backend development": "backend",
    "back end": "backend",
    "front end": "frontend",
    "frontend engineer": "frontend",
    "full-stack": "fullstack",
    "full stack": "fullstack",
    "visual design": "design",
    "ci/cd tools": "ci/cd",
    "tests": "testing",
    "agile software development": "agile",
    "agile methodologies": "agile",
    "agile environment": "agile",
    "agile development": "agile",
    "tdd": "test-driven development",
    "test driven development": "test-driven development",
    "artificial intelligence": "ai",
    "quality assurance": "qa",
    "quality": "qa",
    "maintain": "maintenance",
    "nosql databases": "nosql",
    "sql databases": "sql",
    "sql queries": "sql",
    "nextjs": "next.js",
    "rest apis": "rest",
    "rest api": "rest",
    "mobile development": "mobile",
    "mobile applications": "mobile",
    "designing": "design",
    "test": "testing",
    "deployments": "deployment",
    "problem solving skills": "troubleshooting",
    "bug fixes": "troubleshooting",
    "problem-solving skills": "troubleshooting",
    "problem solving": "troubleshooting",
    "complex problems": "troubleshooting",
    "problem solver": "troubleshooting",
    "troubleshoot": "troubleshooting",
    "debugging": "troubleshooting",
    "maintaining": "maintenance",
    "prototypes": "prototyping",
    "apis": "api",
    "test cases": "testing",
    "vue.js": "vue",
    "vuejs": "vue",
    "web application": "web application development",
    "web app": "web application development",
    "web developer": "web application development",
    "responsive web design": "responsive design",
    "problem": "responsive design",
    "verbal communication skills": "communication",
    "communication skills": "communication",
    "collaboration skills": "collaboration",
    "collaborate": "collaboration",
    "reusable code": "reusability",
    "data visualization": "visualization",
    "architecting": "architecture",
    "technical architecture": "architecture",
    "microservice architecture": "microservices",
    "maintainable code": "maintainability",
    "ci/cd pipielines": "ci/cd",
    "postgres": "postgresql",
    "mentoring": "mentorship",
    "backend services": "backend",
    "ci/cd pipelines": "ci/cd",
    "unit tests": "unit testing",
    "written communication skills": "communication",
    "javascript frameworks": "javascript",
    "ui": "ui/ux",
    "fast-paced environment": "fast-paced",
    "mentor": "mentorship",
    "code reviews": "code review",
    "written communication": "communication",
    "data": "data analysis",
    "analysis": "data analysis",
    "collaborative": "collaboration",
    "test automation": "automated testing",
    "verbal and written communication skills": "communication",
    "spring framework": "spring",
}

for from_keyword, to_keywords in one_to_many_map.items():
    if from_keyword in keyword_map:
        store_value = keyword_map[from_keyword]
        del keyword_map[from_keyword]
        for to_keyword in to_keywords:
            if to_keyword in keyword_map:
                keyword_map[to_keyword] += store_value
            else:
                keyword_map[to_keyword] = store_value

for from_keyword, to_keyword in similarity_map.items():
    if from_keyword in keyword_map:
        if to_keyword in keyword_map:
            keyword_map[to_keyword] += keyword_map[from_keyword]
        else:
            keyword_map[to_keyword] = keyword_map[from_keyword]
        del keyword_map[from_keyword]

categories_map = {
    "JavaScript": "Programming Language",
    "React.js": "Framework",
    "CSS": "Programming Language",
    "HTML": "Programming Language",
    "design": "General Skill",
    "Python": "Programming Language",
    "troubleshooting": "General Skill",
    "TypeScript": "Programming Language",
    "Java": "Programming Language",
    "Node.js": "Framework",
    "design": "General Skill",
    "testing": "General Skill",
    "frontend": "Specialization",
    "fullstack": "Specialization",
    "UI/UX": "Specialization",
    "AWS": "Cloud",
    "Angular": "Framework",
    "SQL": "Programming Language",
    "MySQL": "Database",
    "CI/CD": "Engineering Practice",
    "agile": "Engineering Practice",
    "backend": "Specialization",
    "machine learning": "Specialization",
    "scalability": "Engineering Principle",
    "DevOps": "Specialization",
    "Bootstrap": "UI",
    "clean code": "Engineering Principle",
    "innovation": "Personality Trait",
    "relational databases": "Database",
    "PHP": "Programming Language",
    "interpersonal skills": "General Skill",
    "mobile": "Platform",
    "Android": "Platform",
    "iOS": "Platform",
    "responsive design": "Engineering Principle",
    "Ruby": "Programming Language",
    "mentoring": "General Skill",
    "collaboration skills": "General Skill",
    "time management": "General Skill",
    "Swift": "Programming Language",
    "Windows": "Platform",
    "EC2": "Cloud",
    "flexibility": "Personality Trait",
    "Postman": "Tool",
    "Salesforce": "CRM",
    "Kotlin": "Programming Language",
    "SVN": "Version Control",
    "Ansible": "DevOps",
    "J2EE": "Specification",
    "Visual Studio": "IDE",
    "Spring": "Framework",
    "BitBucket": "Version Control",
    "Hibernate": "Framework",
    "Spring Boot": "Framework",
    "ECS": "Cloud",
    "planning": "General Skill",
    "performance optimization": "Engineering Principle",
    "technical leadership": "General Skill",
    "gRPC": "Framework",
    "Photoshop": "Tool",
    "system design": "Specialization",
    "infrastructure": "Specialization",
    "visualization": "General Skill",
    "Perl": "Programming Language",
    "reusability": "Engineering Principle",
    "positive attitude": "Personality Trait",
    "detail-oriented": "Personality Trait",
    "maintainability": "Engineering Principle",
    "network security": "Specialization",
    "Selenium": "Framework",
    "C": "Programming Language",
    "C++": "Programming Language",
    "self-starter": "Personality Trait",
    "hardware": "Specialization",
    "SASS": "Programming Language",
    "SQL Server": "Database",
    "usability": "Engineering Principle",
    "prototyping": "Engineering Process",
    "scrum": "Engineering Practice",
    "Django": "Framework",
    "jQuery": "Framework",
    "NoSQL": "Database",
    "React Native": "Framework",
    "PostgreSQL": "Database",
    "REST": "Architecture",
    "microservices": "Architecture",
    "Docker": "DevOps",
    "Kubernetes": "DevOps",
    "Vue.js": "Framework",
    "MongoDB": "Database",
    "Terraform": "DevOps",
    "Oracle": "Cloud",
    "Redis": "Database",
    "accessibility": "Engineering Principle",
    ".NET": "Framework",
    "distributed systems": "Computer Science Topics",
    "data structures": "Computer Science Topics",
    "design patterns": "Computer Science Topics",
    "documentation": "Engineering Process",
    "code review": "Engineering Process",
    "Jira": "Tool",
    "Azure": "Cloud",
    "problem-solving": "General Skill",
    "Go": "Programming Language",
    "Redux": "Framework",
    "XML": "Programming Language",
    "performance": "Engineering Principle",
    "GraphQL": "Programming Language",
    "Linux": "Platform",
    "reliability": "Personality Trait",
    "attention to detail": "Personality Trait",
    "monitoring": "Engineering Process",
    "project management": "Engineering Process",
    "mentorship": "Personality Trait",
    "Webpack": "Tool",
    "Maven": "Tool",
    "Entity Framework": "Framework",
    "organizational skills": "General Skill",
    "Git": "Version Control",
    "GCP": "Cloud",
    "C#": "Programming Language",
    "AI": "Specialization",
    "ASP.NET": "Framework",
    "Hadoop": "Tool",
    "Figma": "Tool",
    "SOA": "Architecture",
    "Grafana": "Tool",
    "Cassandra": "Database",
    "Saml": "Programming Language",
    "Flask": "Framework",
    "MVC": "Architecture",
    "wireframes": "Engineering Process",
    "functionality": "Engineering Principle",
    "Jest": "Framework",
    "integration testing": "Engineering Process",
    "marketing": "Engineering Process",
    "HTTP": "Architecture",
    "Ruby on Rails": "Framework",
    "SOAP": "Architecture",
    "documentation": "Engineering Process",
    "analytical skills": "General Skill",
    "time-management": "General Skill",
    "management": "General Skill",
    "QA": "Specialization",
    "Kafka": "Tool",
    "Next.js": "Framework",
    "communication": "General Skill",
    "collaboration": "General Skill",
    "maintenance": "Engineering Process",
    "unit testing": "Engineering Process",
    "algorithms": "Computer Science Topics",
    "Jenkins": "DevOps",
    "test-driven development": "Engineering Practice",
    "GitHub": "Version Control",
    "fast-paced": "Personality Trait",
    "self-motivated": "Personality Trait",
    "data analysis": "Engineering Process",
    "Elasticsearch": "Tool",
    "automated testing": "Specialization",
    "networking": "Specialization",
    "ECS (AWS)": "Cloud",
    "computer vision": "Computer Science Topic",
    "creativity": "Personality Trait",
    "electrical engineering": "Specialization",
    "GitLab": "Version Control",
    "S3 (AWS)": "Cloud",
    "passionate": "Personality Trait",
    "empathy": "Personality Trait",
}

format_map = {
    "react": "React.js",
    "javascript": "JavaScript",
    "css": "CSS",
    "html": "HTML",
    "python": "Python",
    "typescript": "TypeScript",
    "java": "Java",
    "node.js": "Node.js",
    "ui/ux": "UI/UX",
    "aws": "AWS",
    "angular": "Angular",
    "sql": "SQL",
    "mysql": "MySQL",
    "ci/cd": "CI/CD",
    "devops": "DevOps",
    "bootstrap": "Bootstrap",
    "php": "PHP",
    "android": "Android",
    "ios": "iOS",
    "ruby": "Ruby",
    "swift": "Swift",
    "windows": "Windows",
    "ec2": "EC2 (AWS)",
    "postman": "Postman",
    "salesforce": "Salesforce",
    "kotlin": "Kotlin",
    "svn": "SVN",
    "ansible": "Ansible",
    "j2ee": "J2EE",
    "visual studio": "Visual Studio",
    "spring": "Spring",
    "bitbucket": "BitBucket",
    "hibernate": "Hibernate",
    "spring boot": "Spring Boot",
    "ecs": "ECS (AWS)",
    "grpc": "gRPC",
    "photoshop": "Photoshop",
    "perl": "Perl",
    "selenium": "Selenium",
    "c": "C",
    "c++": "C++",
    "sass": "SASS",
    "sql server": "SQL Server",
    "scrum": "Scrum",
    "django": "Django",
    "jquery": "jQuery",
    "nosql": "NoSQL",
    "react native": "React Native",
    "postgresql": "PostgreSQL",
    "rest": "REST",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "vue": "Vue.js",
    "mongodb": "MongoDB",
    "terraform": "Terraform",
    "oracle": "Oracle",
    "redis": "Redis",
    ".net": ".NET",
    "jira": "Jira",
    "azure": "Azure",
    "go": "Go",
    "redux": "Redux",
    "xml": "XML",
    "graphql": "GraphQL",
    "linux": "Linux",
    "webpack": "Webpack",
    "maven": "Maven",
    "entity framework": "Entity Framework",
    "git": "Git",
    "gcp": "GCP",
    "c#": "C#",
    "ai": "AI",
    "asp.net": "ASP.NET",
    "hadoop": "Hadoop",
    "figma": "Figma",
    "soa": "SOA",
    "grafana": "Grafana",
    "cassandra": "Cassandra",
    "saml": "SAML",
    "flask": "Flask",
    "mvc": "MVC",
    "jest": "Jest",
    "ruby on rails": "Ruby on Rails",
    "soap": "SOAP",
    "qa": "QA",
    "http": "HTTP",
    "kafka": "Kafka",
    "next.js": "Next.js",
    "github": "GitHub",
    "elasticsearch": "Elasticsearch",
    "gitlab": "GitLab",
    "ecs": "ECS (AWS)",
    "es6": "ES6",
    "s3": "S3 (AWS)",
    "iot": "IoT",
    "spark": "Spark",
}

for from_format, to_format in format_map.items():
    if from_format in keyword_map:
        keyword_map[to_format] = keyword_map[from_format]
        del keyword_map[from_format]

sorted_items = sorted(keyword_map.items(), key=lambda x: x[1], reverse=False)

filter_out_words = [
    "computer science",
    "benefits",
    "software engineer",
    "equity",
    "equal opportunity employer",
    "diversity",
    "religion",
    "race",
    "technology",
    "sexual orientation",
    "engineers",
    "age",
    "product managers",
    "national origin",
    "color",
    "compensation",
    "implementation",
    "dental",
    "ca",
    "experience",
    "bachelor's degree",
    "tools",
    "parental leave",
    "paid time off",
    "code",
    "tools",
    "marital status",
    "medical",
    "gender identity",
    "sex",
    "technologies",
    "disability",
    "web technologies",
    "veteran status",
    "coding",
    "vision",
    "features",
    "scalable",
    "base salary",
    "vision insurance",
    "san francisco",
    "california",
    "culture",
    "new features",
    "compensation package",
    "building",
    "disability insurance",
    "san jose",
    "investors",
    "dental coverage",
    "growth",
    "skills",
    "determination",
    "salary range",
    "equal opportunity",
    "ancestry",
    "snacks",
    "benefits package",
    "expression",
    "paid holidays",
    "bonus",
    "flexible time off",
    "offices",
    "holidays",
    "citizenship",
    "gender expression",
    "competitive compensation",
    "retirement plan",
    "business",
    "medical coverage",
    "accommodations",
    "tuition reimbursement",
    "bachelor's degree",
    "equal employment opportunity",
    "bugs",
    "vision coverage",
    "employee assistance program",
    "platforms",
    "flexible spending account",
    "genetic information",
    "projects",
    "401(k)",
    "401k",
    "full-time",
    "software engineers",
    "impact",
    "customers",
    "qualifications",
    "feedback",
    "industry trends",
    "base pay",
    "reasonable accommodations",
    "salary",
    "pay range",
    "pregnancy",
    "competitive salary",
    "resume",
    "pto",
    "metrics",
    "medical benefits",
    "continuous improvement",
    "stock options",
    "protected veteran status",
    "implement",
    "health insurance",
    "disability status",
    "remote",
    "libraries",
    "solutions",
    "production",
    "gender",
    "remote work",
    "senior software engineer" "support",
    "location",
    "inclusion",
    "services",
    "build",
    "engineering team",
    "platform",
    "industry experience",
    "tooling",
    "funding",
    "develop",
    "developers",
    "team player",
    "healthcare",
    "discrimination",
    "applications",
    "united states",
    "travel",
    "dental insurance",
    "life insurance",
    "senior software engineer",
    "medical insurance",
    "bachelor's degree",
    "commuter benefits",
    "harassment",
    "frameworks",
]

filtered_words = [
    item for item in sorted_items if item[1] > 9 and item[0] not in filter_out_words
]

category_map = {}
for keyword_tuple in filtered_words:
    if keyword_tuple[0] in categories_map:
        category_map[keyword_tuple[0]] = (
            keyword_tuple[1],
            categories_map[keyword_tuple[0]],
        )
    else:
        category_map[keyword_tuple[0]] = keyword_tuple[1]


# print(category_list)

# count_strings = ["responsive design", "rwd", "responsive web design"]
# for count_string in count_strings:
#     if count_string in keyword_map:
#         print(f"{count_string}: {keyword_map[count_string]}")
#     else:
#         print(f"{count_string}: 0")

# for item in category_list:
#     if fuzz.ratio(item[0], "next") > 30:
#         print(item)

with open(f"keywords_counted/{filename}.json", "w", encoding="utf-8") as file:
    json.dump(category_map, file, indent=4)
