filter_out_words = [
    "computer science",
    "benefits",
    "software engineer",
    "equity",
    "equal opportunity employer",
    "diversity",
    "religion",
    "race",
    "technology",
    "sexual orientation",
    "engineers",
    "age",
    "product managers",
    "national origin",
    "color",
    "compensation",
    "implementation",
    "dental",
    "ca",
    "experience",
    "bachelor's degree",
    "tools",
    "parental leave",
    "paid time off",
    "code",
    "tools",
    "marital status",
    "medical",
    "gender identity",
    "sex",
    "technologies",
    "disability",
    "web technologies",
    "veteran status",
    "coding",
    "vision",
    "features",
    "scalable",
    "base salary",
    "vision insurance",
    "san francisco",
    "california",
    "culture",
    "new features",
    "compensation package",
    "building",
    "disability insurance",
    "san jose",
    "investors",
    "dental coverage",
    "growth",
    "skills",
    "determination",
    "salary range",
    "equal opportunity",
    "ancestry",
    "snacks",
    "benefits package",
    "expression",
    "paid holidays",
    "bonus",
    "flexible time off",
    "offices",
    "holidays",
    "citizenship",
    "gender expression",
    "competitive compensation",
    "retirement plan",
    "business",
    "medical coverage",
    "accommodations",
    "tuition reimbursement",
    "bachelor's degree",
    "equal employment opportunity",
    "bugs",
    "vision coverage",
    "employee assistance program",
    "platforms",
    "flexible spending account",
    "genetic information",
    "projects",
    "401(k)",
    "401k",
    "full-time",
    "software engineers",
    "impact",
    "customers",
    "qualifications",
    "feedback",
    "industry trends",
    "base pay",
    "reasonable accommodations",
    "salary",
    "pay range",
    "pregnancy",
    "competitive salary",
    "resume",
    "pto",
    "metrics",
    "medical benefits",
    "continuous improvement",
    "stock options",
    "protected veteran status",
    "implement",
    "health insurance",
    "disability status",
    "remote",
    "libraries",
    "solutions",
    "production",
    "gender",
    "remote work",
    "senior software engineer" "support",
    "location",
    "inclusion",
    "services",
    "build",
    "engineering team",
    "platform",
    "industry experience",
    "tooling",
    "funding",
    "develop",
    "developers",
    "team player",
    "healthcare",
    "discrimination",
    "applications",
    "united states",
    "travel",
    "dental insurance",
    "life insurance",
    "senior software engineer",
    "medical insurance",
    "bachelor's degree",
    "commuter benefits",
    "harassment",
    "frameworks",
    "web applications",
    "electrical",
    "electrical engineering",
    "software development",
    "development",
    "api",
    "web application development",
    "web development",
    "web application",
    "web app",
    "web developer",
    "web services",
    "engineering",
    "best practices",
    "software engineering",
    "databases",
    "architecture",
    "integration",
    "prioritization",
    "users",
    "software",
    "infrastructure",
    "support",
    "programming languages",
    "computer engineering",
    "requirements",
    "information technology",
    "coding standards",
    "new technologies",
    "cross-functional teams",
    "version control systems",
    "education",
    "designers",
    "software developer",
    "programming",
    "information systems",
    "product",
    "research",
    "learning",
    "analytics",
    "software solutions",
    "software development lifecycle",
    "application development",
    "code quality",
    "workflows",
    "emerging technologies",
    "sdlc",
    "cloud technologies",
    "business requirements",
    "cloud",
    "software applications",
    "database",
    "developing",
    "systems",
    "marketing",
    "standards",
    "software design",
    "cloud platforms",
    "wireframes",
    "scripting languages",
    "certifications",
    "portfolio",
    "web api",
    "technical solutions",
    "ownership",
    "stakeholders" "stored procedures",
    "master's degree",
    "technical specifications"
    "professional development"
    "scripting"
    "technical support",
    "products",
    "processes",
    "procedures",
    "operating systems",
    "cloud infrastructure",
    "schedule",
    "team environment",
    "security clearance",
    "independent work",
    "web apis",
    "integrations",
    "operations",
    "reports",
    "technical design",
    "version control",
    "cloud services",
    "web",
    "software development life cycle",
    "web-based applications",
    "specifications",
    "reporting",
    "contract",
    "enhancements",
    "customer service",
    "scale",
    "bachelor\u2019s degree",
    "authentication",
    "containerization",
    "interfaces",
    "websites",
    "organization",
    "hardware",
    "source control",
    "user interface",
    "infrastructure as code",
    "data pipelines",
    "secret clearance",
    "technical requirements",
    "developer",
    "work location",
    "team",
    "multitasking",
    "monday to friday",
    "api development",
    "industry best practices",
    "it",
    "technical skills",
    "industry standards",
    "engineering teams",
    "saas",
    "mockups",
    "customer experience",
    "related field",
    "cloud computing",
    "product development",
    "fast-paced environment",
    "stakeholders",
    "technical support",
    "technical specifications",
    "stored procedures",
    "professional development",
    "integrity",
    "collaborative environment",
    "technical issues",
    "development team",
    "us citizenship",
    "us citizen",
    "guidance",
    "multi-tasking",
    "containers",
    "critical thinking",
    "dashboards",
    "implementing",
    "business analysts",
    "software systems",
    "u.s. citizenship",
    "architect",
    "design reviews",
    "health savings account",
    "deadlines",
    "data analytics",
    "software architecture",
    "dns",
    "technical expertise",
    "prioritize",
    "authorization",
    "in person",
    "technical lead",
    "flexible schedule" "work experience",
    "rdbms",
    "data scientists",
    "business needs",
    "401(k) plans",
    "analyze",
    "pay",
    "8 hour shift",
    "installation",
    "data science",
    "000.00 per year",
    "coaching",
    "hybrid",
    "relational database",
    "firewalls",
    "e-commerce",
    "risk management",
    "product owners",
    "va",
    "clients",
    "reliable",
    "business processes",
    "innovative solutions",
    "application architecture",
    "automated tests",
    "content management systems",
]
