similarity_map = {
    "front-end": "frontend",
    "reactjs": "react",
    "css3": "css",
    "html5": "html",
    "angularjs": "angular",
    "angular.js": "angular",
    "react.js": "react",
    "node": "node.js",
    "nodejs": "node.js",
    "node js": "node.js",
    "continuous integration": "ci/cd",
    "continuous deployment": "ci/cd",
    "continuous delivery": "ci/cd",
    "user experience": "ui/ux",
    "performance optimization": "performance",
    "azure devops": "azure",
    "ux": "ui/ux",
    "user experiences": "ui/ux",
    "ui design": "ui/ux",
    "ux design": "ui/ux",
    "golang": "go",
    "oop": "object-oriented programming",
    "object oriented programming": "object-oriented programming",
    "object-oriented design": "object-oriented programming",
    "amazon web services": "aws",
    "google cloud": "gcp",
    "google cloud platform": "gcp",
    "front-end technologies": "frontend",
    "front-end development": "frontend",
    "frontend development": "frontend",
    "back-end": "backend",
    "back-end development": "backend",
    "backend development": "backend",
    "back end": "backend",
    "front end": "frontend",
    "frontend engineer": "frontend",
    "full-stack": "fullstack",
    "full stack": "fullstack",
    "visual design": "design",
    "ci/cd tools": "ci/cd",
    "tests": "testing",
    "agile software development": "agile",
    "agile methodologies": "agile",
    "agile environment": "agile",
    "agile development": "agile",
    "tdd": "test-driven development",
    "test driven development": "test-driven development",
    "artificial intelligence": "ai",
    "quality assurance": "qa",
    "quality": "qa",
    "maintain": "maintenance",
    "nosql databases": "nosql",
    "sql databases": "sql",
    "sql queries": "sql",
    "nextjs": "next.js",
    "rest apis": "rest",
    "rest api": "rest",
    "mobile development": "mobile",
    "mobile applications": "mobile",
    "designing": "design",
    "test": "testing",
    "deployments": "deployment",
    "problem solving skills": "problem-solving",
    "bug fixes": "problem-solving",
    "problem-solving skills": "problem-solving",
    "problem solving": "problem-solving",
    "complex problems": "problem-solving",
    "problem solver": "problem-solving",
    "troubleshoot": "problem-solving",
    "debugging": "problem-solving",
    "maintaining": "maintenance",
    "prototypes": "prototyping",
    "apis": "api",
    "test cases": "testing",
    "vue.js": "vue",
    "vuejs": "vue",
    "responsive design": "responsive web design",
    "verbal communication skills": "communication",
    "verbal communication": "communication",
    "communication skills": "communication",
    "collaboration skills": "collaboration",
    "collaborate": "collaboration",
    "reusable code": "reusability",
    "data visualization": "visualization",
    "architecting": "architecture",
    "technical architecture": "architecture",
    "microservice architecture": "microservices",
    "maintainable code": "maintainability",
    "postgres": "postgresql",
    "mentoring": "mentorship",
    "backend services": "backend",
    "ci/cd pipelines": "ci/cd",
    "unit tests": "unit testing",
    "written communication skills": "communication",
    "javascript frameworks": "javascript",
    "ui": "ui/ux",
    "user interfaces": "ui/ux",
    "mentor": "mentorship",
    "code reviews": "code review",
    "written communication": "communication",
    "data": "data analysis",
    "analysis": "data analysis",
    "collaborative": "collaboration",
    "test automation": "automated testing",
    "verbal and written communication skills": "communication",
    "spring framework": "spring",
    ".net core": ".net",
    "restful apis": "rest",
    ".net framework": ".net",
    "web design": "ui/ux",
    "technical documentation": "documentation",
    "technical leadership": "leadership",
    "microsoft sql server": "sql server",
    "ms sql server": "sql server",
    "full stack developer": "fullstack",
    "restful web services": "rest",
    "debug": "problem-solving",
    "agile methodology": "agile",
    "micrsoft azure": "azure",
    "agile development methodologies": "agile",
    ".net developer": ".net",
    "scss": "sass",
    "test plans": "testing",
    "microsoft azure": "azure",
    "full stack development": "fullstack",
    "product managers": "project management",
    "software testing": "testing",
    "angular js": "Angular",
    "ui/ux design": "ui/ux",
    "ci/cd pipeline": "ci/cd",
    "leadership skills": "leadership",
    "react js": "react",
    "restful api": "rest",
    "full-stack development": "fullstack",
    "automated tests": "testing",
    "ms sql": "sql server",
    "spring mvc": "spring",
    "agile development methodology": "agile",
    "oral communication": "communication",
    "full stack engineer": "fullstack",
    "team collaboration": "collaboration",
    "java development": "java",
    "html 5": "h5ml",
    "agile team": "agile",
    "js": "javascript",
    "devops practices": "devops",
    "subversion": "svn",
    "springboot": "spring boot",
    "front end developer": "frontend",
}
